window.GEO_DUEL_COUNTRIES = [
  { name: "France", capital: "Paris", flag: "🇫🇷", lat: 46.23, lon: 2.21 },
  { name: "Espagne", capital: "Madrid", flag: "🇪🇸", lat: 40.46, lon: -3.75 },
  { name: "Portugal", capital: "Lisbonne", flag: "🇵🇹", lat: 39.4, lon: -8.22 },
  { name: "Italie", capital: "Rome", flag: "🇮🇹", lat: 41.87, lon: 12.57 },
  { name: "Allemagne", capital: "Berlin", flag: "🇩🇪", lat: 51.16, lon: 10.45 },
  { name: "Royaume-Uni", capital: "Londres", flag: "🇬🇧", lat: 55.38, lon: -3.44, aliases: ["United Kingdom"] },
  { name: "Irlande", capital: "Dublin", flag: "🇮🇪", lat: 53.41, lon: -8.24 },
  { name: "Norvege", capital: "Oslo", flag: "🇳🇴", lat: 60.47, lon: 8.47 },
  { name: "Suede", capital: "Stockholm", flag: "🇸🇪", lat: 60.13, lon: 18.64 },
  { name: "Pologne", capital: "Varsovie", flag: "🇵🇱", lat: 51.92, lon: 19.15 },
  { name: "Grece", capital: "Athenes", flag: "🇬🇷", lat: 39.07, lon: 21.82 },
  { name: "Turquie", capital: "Ankara", flag: "🇹🇷", lat: 38.96, lon: 35.24 },
  { name: "Maroc", capital: "Rabat", flag: "🇲🇦", lat: 31.79, lon: -7.09 },
  { name: "Algerie", capital: "Alger", flag: "🇩🇿", lat: 28.03, lon: 1.66 },
  { name: "Egypte", capital: "Le Caire", flag: "🇪🇬", lat: 26.82, lon: 30.8 },
  { name: "Afrique du Sud", capital: "Pretoria", flag: "🇿🇦", lat: -30.56, lon: 22.94 },
  { name: "Nigeria", capital: "Abuja", flag: "🇳🇬", lat: 9.08, lon: 8.68 },
  { name: "Kenya", capital: "Nairobi", flag: "🇰🇪", lat: -0.02, lon: 37.91 },
  { name: "Inde", capital: "New Delhi", flag: "🇮🇳", lat: 20.59, lon: 78.96 },
  { name: "Chine", capital: "Pekin", flag: "🇨🇳", lat: 35.86, lon: 104.2 },
  { name: "Japon", capital: "Tokyo", flag: "🇯🇵", lat: 36.2, lon: 138.25 },
  { name: "Coree du Sud", capital: "Seoul", flag: "🇰🇷", lat: 35.9, lon: 127.77 },
  { name: "Indonesie", capital: "Jakarta", flag: "🇮🇩", lat: -0.79, lon: 113.92 },
  { name: "Thailande", capital: "Bangkok", flag: "🇹🇭", lat: 15.87, lon: 100.99 },
  { name: "Vietnam", capital: "Hanoi", flag: "🇻🇳", lat: 14.06, lon: 108.28 },
  { name: "Australie", capital: "Canberra", flag: "🇦🇺", lat: -25.27, lon: 133.78 },
  { name: "Nouvelle-Zelande", capital: "Wellington", flag: "🇳🇿", lat: -40.9, lon: 174.89 },
  { name: "Etats-Unis", capital: "Washington", flag: "🇺🇸", lat: 37.09, lon: -95.71, aliases: ["United States of America", "United States"] },
  { name: "Canada", capital: "Ottawa", flag: "🇨🇦", lat: 56.13, lon: -106.35 },
  { name: "Mexique", capital: "Mexico", flag: "🇲🇽", lat: 23.63, lon: -102.55 },
  { name: "Bresil", capital: "Brasilia", flag: "🇧🇷", lat: -14.24, lon: -51.93 },
  { name: "Argentine", capital: "Buenos Aires", flag: "🇦🇷", lat: -38.42, lon: -63.62 },
  { name: "Chili", capital: "Santiago", flag: "🇨🇱", lat: -35.68, lon: -71.54 },
  { name: "Colombie", capital: "Bogota", flag: "🇨🇴", lat: 4.57, lon: -74.3 },
  { name: "Perou", capital: "Lima", flag: "🇵🇪", lat: -9.19, lon: -75.02 },
  { name: "Russie", capital: "Moscou", flag: "🇷🇺", lat: 61.52, lon: 105.32, aliases: ["Russia"] },
  { name: "Ukraine", capital: "Kyiv", flag: "🇺🇦", lat: 48.38, lon: 31.17 },
  { name: "Arabie saoudite", capital: "Riyad", flag: "🇸🇦", lat: 23.89, lon: 45.08 },
  { name: "Iran", capital: "Teheran", flag: "🇮🇷", lat: 32.43, lon: 53.69 },
  { name: "Pakistan", capital: "Islamabad", flag: "🇵🇰", lat: 30.38, lon: 69.35 },
  { name: "Islande", capital: "Reykjavik", flag: "🇮🇸", lat: 64.96, lon: -19.02 },
  { name: "Cuba", capital: "La Havane", flag: "🇨🇺", lat: 21.52, lon: -77.78 },
  { name: "Madagascar", capital: "Antananarivo", flag: "🇲🇬", lat: -18.77, lon: 46.87 },
  { name: "Suisse", capital: "Berne", flag: "🇨🇭", lat: 46.82, lon: 8.23 },
  { name: "Pays-Bas", capital: "Amsterdam", flag: "🇳🇱", lat: 52.13, lon: 5.29, aliases: ["Netherlands"] },
  { name: "Belgique", capital: "Bruxelles", flag: "🇧🇪", lat: 50.5, lon: 4.47 },
  { name: "Danemark", capital: "Copenhague", flag: "🇩🇰", lat: 56.26, lon: 9.5 },
  { name: "Finlande", capital: "Helsinki", flag: "🇫🇮", lat: 61.92, lon: 25.75 },
  { name: "Autriche", capital: "Vienne", flag: "🇦🇹", lat: 47.52, lon: 14.55 },
  { name: "Republique tcheque", capital: "Prague", flag: "🇨🇿", lat: 49.82, lon: 15.47, aliases: ["Czechia"] }
];

const GEO_DUEL_MAP_NAMES = {
  France: ["France"],
  Espagne: ["Spain"],
  Portugal: ["Portugal"],
  Italie: ["Italy"],
  Allemagne: ["Germany"],
  "Royaume-Uni": ["United Kingdom", "England", "Scotland", "Wales", "Northern Ireland"],
  Irlande: ["Ireland"],
  Norvege: ["Norway"],
  Suede: ["Sweden"],
  Pologne: ["Poland"],
  Grece: ["Greece"],
  Turquie: ["Turkey"],
  Maroc: ["Morocco"],
  Algerie: ["Algeria"],
  Egypte: ["Egypt"],
  "Afrique du Sud": ["South Africa"],
  Nigeria: ["Nigeria"],
  Kenya: ["Kenya"],
  Inde: ["India"],
  Chine: ["China"],
  Japon: ["Japan"],
  "Coree du Sud": ["South Korea", "Korea"],
  Indonesie: ["Indonesia"],
  Thailande: ["Thailand"],
  Vietnam: ["Vietnam"],
  Australie: ["Australia"],
  "Nouvelle-Zelande": ["New Zealand"],
  "Etats-Unis": ["United States of America", "United States", "USA"],
  Canada: ["Canada"],
  Mexique: ["Mexico"],
  Bresil: ["Brazil"],
  Argentine: ["Argentina"],
  Chili: ["Chile"],
  Colombie: ["Colombia"],
  Perou: ["Peru"],
  Russie: ["Russia"],
  Ukraine: ["Ukraine"],
  "Arabie saoudite": ["Saudi Arabia"],
  Iran: ["Iran"],
  Pakistan: ["Pakistan"],
  Islande: ["Iceland"],
  Cuba: ["Cuba"],
  Madagascar: ["Madagascar"],
  Suisse: ["Switzerland"],
  "Pays-Bas": ["Netherlands"],
  Belgique: ["Belgium"],
  Danemark: ["Denmark"],
  Finlande: ["Finland"],
  Autriche: ["Austria"],
  "Republique tcheque": ["Czech Republic", "Czechia"]
};

window.GEO_DUEL_COUNTRIES.forEach((country) => {
  country.geoNames = GEO_DUEL_MAP_NAMES[country.name] || [country.name];
});
